# Generated by Django 3.2.7 on 2021-09-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SignUpUser',
        ),
        migrations.AlterModelTable(
            name='signupuser',
            table='signupusers',
        ),
    ]
